added deploy stuff

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,8 +7,21 @@ on:
   workflow_dispatch: # Manual trigger
 
 jobs:
+  set-vars:
+    runs-on: ubuntu-latest
+    outputs:
+      AWS_ACCOUNT_ID: ${{ steps.set-vars.outputs.AWS_ACCOUNT_ID }}
+      AWS_REGION: ${{ steps.set-vars.outputs.AWS_REGION }}
+    steps:
+      - name: Set environment variables
+        id: set-vars
+        run: |
+          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
+          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
+
   deploy:
     runs-on: ubuntu-latest
+    needs: set-vars
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -25,16 +38,17 @@ jobs:
 
       - name: Clean CDK Context
         run: |
+          cd CDK
           rm -rf node_modules/.cdk
 
       - name: Bootstrap CDK Environment
         run: |
           cd CDK
-          npx cdk bootstrap aws://654654232198/us-east-1
+          npx cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: "us-east-1"
+          AWS_REGION: ${{ env.AWS_REGION }}
 
       - name: Deploy CDK Stack
         id: deploy
@@ -44,4 +58,21 @@ jobs:
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: "us-east-1"
+          AWS_REGION: ${{ env.AWS_REGION }}
+
+      - name: Output ECR URI
+        id: output-ecr-uri
+        run: |
+          set -x  # Enable command tracing
+          # Print current AWS CLI configuration
+          aws configure list
+          # Print AWS CLI version
+          aws --version
+          # Describe stacks and handle potential errors
+          ECR_URI=$(aws cloudformation describe-stacks --stack-name IoTStack --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryUri'].OutputValue" --output text || echo "Failed to get ECR URI")
+          echo "ECR_URI=$ECR_URI"
+          echo "::set-output name=ecr-uri::$ECR_URI"
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ env.AWS_REGION }}
