changed deploy and deploy-build

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -6,9 +6,6 @@ on:
     types:
       - completed
 
-env:
-  TEST: 654654232198.dkr.ecr.us-east-1.amazonaws.com/my-iot-gps-app
-
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
@@ -17,6 +14,30 @@ jobs:
       contents: read
 
     steps:
+      - name: Output ECR URI
+        id: output-ecr-uri
+        run: |
+          set -x  # Enable command tracing
+          # Print current AWS CLI configuration
+          aws configure list
+          # Print AWS CLI version
+          aws --version
+          # Describe stacks and handle potential errors
+          ECR_URI=$(aws cloudformation describe-stacks --stack-name IoTStack --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryUri'].OutputValue" --output text || echo "Failed to get ECR URI")
+          echo "ECR_URI=$ECR_URI"
+          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+
+      - name: Print ECR URI
+        run: echo "ECR_URI=${{ env.ECR_URI }}"
+
+      - name: META_START_DATA
+        run: |
+          echo ACTION: $HITHUB_ACTION
+          echo GITHuB_ACTION_REPOSITORY $GITHUB_ACTION_REPOSITORY
+          echo GITHuB_ACTION_REPOSITORY $GITHUB_ACTION_REPOSITORY
+
       - name: Checkout code
         uses: actions/checkout@v3
 
@@ -45,5 +66,5 @@ jobs:
       - name: Build and Push Docker image
         run: |
           echo "Building Docker image from IoT_GPS"
-          docker build -t $TEST:latest -f IoTMockSensors/IoT_GPS/Dockerfile IoTMockSensors/IoT_GPS
-          docker push $TEST:latest
+          docker build -t ${{ env.ECR_URI }}:latest -f IoTMockSensors/IoT_GPS/Dockerfile IoTMockSensors/IoT_GPS
+          docker push ${{ env.ECR_URI }}:latest
